// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Serialization
{

public enum MessageID : sbyte
{
  None = 0,
  SandboxState = 1,
  OrderBet = 2,
  OrderPlayCard = 3,
};


}
