// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Serialization
{

public enum Sigil : sbyte
{
  Spade = 0,
  Club = 1,
  Heart = 2,
  Diamond = 3,
};


}
