// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Serialization
{

public enum State : sbyte
{
  Initialize = 0,
  Betting = 1,
  Fold = 2,
  EndGame = 3,
  Unkown = 4,
};


}
